### ISSUE TITLE
Missing Items - Space Marines - Chapter Relics

### ISSUE THREAD

**Issue by ghost** [BSData/wh40k-7th-edition#2244]
Under Raven guard Chapter relics, Ex Tenebris and Nihilus are missing from the wargear options

**Comment by DrTobogganMD** [comment]
Fixed with #2219

**Comment by ghost** [comment]
No it's not, I've started a new rosta and they still don't show up. They disappeard with the last update and have not come back.

**Comment by DrTobogganMD** [comment]
Are you working with the catalog from the repository on Windows or via phone and appspot?

**Comment by ghost** [comment]
I'm using it from appspot

**Comment by DrTobogganMD** [comment]
Appspot has not yet been updated with the latest changes.  We usually compile all the bugfixes every week or two and push it to appspot.

**Comment by ghost** [comment]
ahhh ! that explains it then :-) Thank you for your help, I'll wait for the update on there.
