### ISSUE TITLE
[Anon] Bug report: Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3339]
**File:** Adepta Sororitas.catz

**BattleScribe version:** 2.10.65

**Platform:** Windows

**Dropbox:** No

**Description:** Hi, 

there is a prblem with the Soratitas Command Squad. If I try to get them a transport as a dedicated transport, it quotes: "Sororitas Command Squad has 1 too many selections from Sororitas Command Squad (maximum 5)". It's not a huge problem, but still annoying to keep in mind that there is actually no problem with this squad.

Would you mind, to fix it some time? 
Thank you so much.

**Comment by alphalas** [comment]
What is your version number for the cat? This should have been fixed a few releases ago.

**Comment by GenWilhelm** [comment]
I can confirm this is happening on v2014.

**Comment by Commisar** [comment]
I still get this error too. I was ignoring it because I saw you thought you had dealt with it, and assumed I had done something wrong.

**Comment by alphalas** [comment]
I though I had dealt with it too tbh - I'll recheck once I'm home
